// Generated by CoffeeScript 1.10.0
(function() {
  var ffi, fs, simpleCallback;

  fs = require('fs');

  ffi = require('ffi');

  simpleCallback = ffi.Function('void', []);

  module.exports = function(libname, file) {
    var f, i, j, lib, ref;
    lib = JSON.parse(fs.readFileSync(file));
    for (f in lib) {
      for (i = j = 0, ref = lib[f][1].length - 1; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
        if (lib[f][1][i] === 'void') {
          lib[f][1][i] = simpleCallback;
        }
      }
    }
    return ffi.Library(libname, lib);
  };

}).call(this);
